version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '0 12 8,23 * *'
    target-branch: '2026-September'
    commit-message:
      prefix: 'Update - GH Actions'

    groups:
      github-actions-all:
        patterns:
          - '*'
