#!/usr/bin/env bash
#
# Build tests for GD32F103RC_voxelab_maple
#

# exit on first failure
set -e

#
# Build with included configs
#
use_example_configs "Voxelab Aquila/Default"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Aquila GD32 - ProUI Default" "$3"

use_example_configs "Voxelab Aquila/MM"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Aquila GD32 - ProUI Manual Mesh (MM)" "$3"

use_example_configs "Voxelab Aquila/BLT"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Aquila GD32 - ProUI Bilinear (BLT)" "$3"

use_example_configs "Voxelab Aquila/UBL"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Aquila GD32 - ProUI Unified (UBL)" "$3"

use_example_configs "Voxelab Aquila/X3"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Aquila GD32 - ProUI X3" "$3"

use_example_configs "Voxelab Aquila/UBL"
opt_set CONTROLLERFAN_SPEED_MIN 40 CONTROLLERFAN_SPEED_MAX 127 \
        E0_AUTO_FAN_PIN UART5_TX_PIN CONTROLLER_FAN_PIN UART5_RX_PIN
# opt_disable
opt_enable USE_CONTROLLER_FAN CONTROLLER_FAN_EDITABLE
opt_add FAN_KICKSTART_EDITABLE FAN_KICKSTART_MENU AUTO_FAN_EDITABLE AUTO_FAN_MENU
exec_test $1 $2 "Aquila GD32 - ProUI Unified (UBL) Adv Misc Fans" "$3"
