name: 🪲 Report a bug
description: Create a bug report to help improve this Firmware
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Details
        #### You can also use this form to describe a issue or suggest any fix no matter how simple, it doesn't have to be a 'bug' per say.

  - type: dropdown
    attributes:
      label: Did you test the latest release build?
      description: >-
        Always try the [latest](https://github.com/classicrocker883/MRiscoCProUI/releases/latest) - most recently updated firmware
      options:
        - Yes, and the problem still exists.
        - No, but I will try it!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Description

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Be clear and concise of the
        problem and include as many details as possible.

        Use ` ```y ` before and  ` ``` ` after (on its own line) when pasting formatted code.
      placeholder: |
        A does B, supposed to do C.
        X doesn't work.

        Please describe the steps needed to reproduce the issue.
        1. [First Step] ...
        2. [Second Step] ...
        3. [ect] ...

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Your Setup

  - type: dropdown
    attributes:
      label: Printer Model
      description: >-
        Which Printer are you using?
      options:
        - Voxelab Aquila
        - Creality Ender-3
        - Other (explain below)

  - type: input
    attributes:
      label: Model Type
      description: >-
        Aquila [OG, X2, X3, S2, S3, D1, Pro]

        Ender-3 [V2, S1, Neo, Pro, Max]

  - type: dropdown
    attributes:
      label: Your Mainboard
      description: >-
        Which Chip?
      options:
        - Aquila GD32
        - Aquila N32
        - Aquila HC32
        - Creality v4.2.7/4.2.2 F103RET6
        - Creality v2.4 F401RCT6 (S1)
        - Creality E3 F401RET6
        - BTT SKR MINI E3 v3.0.1
        - BTT SKR MINI E3 v3.0
        - BTT SKR MINI E3 v2.0/1.2/1.0
        - Other (other than listed)

  - type: input
    attributes:
      label: Other Mainboard Type
      description: >-
        If not listed above

        (Optional) Enter chip full model number

  - type: input
    attributes:
      label: Add-ons that could be involved
      description: (BL/3D/CR)-Touch, Rasp-pi, Slicer

  - type: dropdown
    attributes:
      label: ProUI-EX | Extra Features?
      description: >-
        Are you using ProUI-EX?
      options:
        - "Yes"
        - "No (formerly NoPro)"
    validations:
      required: true


  - type: dropdown
    attributes:
      label: Bed Leveling
      description: >-
        What kind of bed leveling are you using?
      options:
        - UBL - Unified Bed Leveling
        - BLT - BL Touch Bilinear mesh
        - MM - Manual Mesh Bed Leveling
        - Default - No Probe / No Bed Leveling
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Attachments

  - type: checkboxes
    attributes:
      label: Did you include your own configuration files?
      options:
        - label: A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

  - type: markdown
    attributes:
      value: |
        ### Optional items to include:
        - Log output from the host. (`M111 S247` for maximum logging.)
        - Images or videos demonstrating the problem, if it helps to make it clear.
        - A G-Code file that exposes the problem, if not affecting _all_ G-code.

  - type: textarea
    attributes:
      label: Additional information & file uploads
      description: >-
        If you've made any other modifications to the firmware, please describe them in detail.

        Don't forget to put ` ```y ` before and  ` ``` ` after (on its own line) when pasting formatted code.
