#
# check-pr.yml
# Close PRs directed at release branches
#

name: PR Bad Target

on:
  pull_request_target:
    types: [opened]

jobs:
  bad_target:
    name: PR Bad Target
    if: github.repository == 'classicrocker883/MRiscoCProUI'

    runs-on: ubuntu-latest

    steps:
    - name: Close invalid PR
      if: ${{ github.event.pull_request.base.ref != '2024-December' }}
      uses: superbrothers/close-pull-request@v3.1.2
      with:
        comment: >
          Thanks for your contribution!

          Unfortunately, we can only accept PRs targeting the default branch.
          To fix this:
          1. Rebase your branch onto `2024-December`.
          2. Submit a new PR targeting `2024-December`.

          Please redo this PR starting with the most recent branch and be careful to target it when resubmitting the PR.

          See [this page](https://marlinfw.org/docs/development/getting_started_pull_requests.html) for full instructions.
