#
# ci-validate-lines.yml
# Validate that all text files are unchanged by linesformat.py
#

name: CI - Validate Source Files

on:
  pull_request:
    branches:
      - 2026-March
  push:
    branches:
      - 2026-March

jobs:
  validate_source_files:
    name: Validate Source Files
    if: github.repository == 'classicrocker883/MRiscoCProUI'

    runs-on: ubuntu-latest

    steps:
      - name: Check out the PR
        uses: actions/checkout@v6.0.2

      - name: Cache node_modules
        uses: actions/cache@v5.0.3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-lines-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-lines-

      - name: Validate text file formatting
        run: |
          npm install --save-dev prettier
          make validate-lines -j
