# .github/workflows/release-matrix.yml
name: Dispatch to Config Builds

on:
  release:
    types: [released]

jobs:
  build-ender3:
    if: contains(github.event.release.tag_name, 'ender3')
    uses: classicrocker883/MRiscoCProUI/.github/workflows/compile-configs-Ender.yml@HC32-May-Test
    with:
      target: ender3

  build-hc32:
    if: contains(github.event.release.tag_name, 'HC32')
    uses: classicrocker883/MRiscoCProUI/.github/workflows/compile-configs-HC32.yml@HC32-May-Test
    with:
      target: HC32
