name: Aquila C2 Build Configs

######################### Aquila #########################

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  Build-C2-Default-MM-N32:            # CR10 LCD Default/MM for N32
    name: Build C2 Default/MM Files N32
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abl: [MM,Default]
        inshape: [true,false]
        temp: [true,false]
        t5: [true,false]
        t13: [true,false]
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20
    - name: Cache pip
      uses: actions/cache@v4.2.3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4.2.3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Select Python 3.13
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'
    - name: Install PlatformIO
      run: |
        python3 -m pip install --upgrade pip wheel platformio
    - name: Run PlatformIO
      id: build_configs
      run: |
        if ($IS); then ISTMP=-IS; else ISTMP=; fi;
        if ($TP); then TPTMP=-MPC; else TPTMP=; fi;
        if ($T5); then STMP=_SPDY5; else STMP=; fi;
        if ($T13); then TTMP=_SPRT13; else TTMP=; fi;
        > Marlin/Configuration.h
        > Marlin/Configuration_adv.h
        > Marlin/Version.h
        if [ "$ABL" = Default ]; then
        cp configurations/Voxelab\ Aquila/Default/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila/Default/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila/Default/Version.h Marlin/Version.h
        elif [ "$ABL" = MM ]; then
        cp configurations/Voxelab\ Aquila/MM/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila/MM/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila/MM/Version.h Marlin/Version.h
        fi;
        echo "filename=C2_N32${STMP}${TTMP}_${ABL}${ISTMP}${TPTMP}$(date +"-%m-%d").bin" >> $GITHUB_OUTPUT
        sed -i "s/default_envs =.*/default_envs = N32F103RC_voxelab_maple/" platformio.ini
        sed -i "s/.*#define REVERSE_ENCODER_DIRECTION/\/\/#define REVERSE_ENCODER_DIRECTION/" Marlin/Configuration.h
        sed -i "s/.*#define DWIN_LCD_PROUI/\/\/#define DWIN_LCD_PROUI/" Marlin/Configuration.h
        sed -i "s/.*#define CR10_STOCKDISPLAY/#define CR10_STOCKDISPLAY/" Marlin/Configuration.h
        sed -i "s/.*#define LCD_BACKLIGHT_TIMEOUT_MINS.*/\/\/#define LCD_BACKLIGHT_TIMEOUT_MINS/" Marlin/Configuration_adv.h
        if ($IS); then STEMP=; else STEMP='\/\/'; fi;
        sed -i "s/.*#define INPUT_SHAPING_X/${STEMP}#define INPUT_SHAPING_X/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Y/${STEMP}#define INPUT_SHAPING_Y/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Z/${STEMP}#define INPUT_SHAPING_Z/" Marlin/Configuration_adv.h
        if ($TP); then PTEMP='\/\/'; MTEMP=; else PTEMP=; MTEMP='\/\/'; fi;
        sed -i "0,/^#define PIDTEMP/ s/.*#define PIDTEMP/${PTEMP}#define PIDTEMP/" Marlin/Configuration.h
        sed -i "s/.*#define MPCTEMP/${MTEMP}#define MPCTEMP/" Marlin/Configuration.h
        if ($T5); then THMP="5"; DSMP="98"; elif ($T13); then THMP="13"; DSMP="424.9"; else THMP="1"; DSMP="98"; fi;
        sed -i "s/^#define TEMP_SENSOR_0.*/#define TEMP_SENSOR_0 ${THMP}/" Marlin/Configuration.h
        sed -i "s/.*#define DEFAULT_AXIS_STEPS_PER_UNIT.*/#define DEFAULT_AXIS_STEPS_PER_UNIT { 80, 80, 400, ${DSMP} }/" Marlin/Configuration.h
        pio run
        mkdir temp
        mv .pio/build/N32F103RC_voxelab_maple/*.bin temp/build.bin
      env:
        ABL: ${{ matrix.abl }}
        IS: ${{ matrix.inshape }}
        TP: ${{ matrix.temp }}
        T5: ${{ matrix.t5 }}
        T13: ${{ matrix.t13 }}
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload A Release Asset
      uses: classicrocker883/upload-a-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: temp/build.bin
        asset_name: ${{ steps.build_configs.outputs.filename }}
        asset_content_type: application/x-binary
  Build-C2-Default-MM-HC32:            # CR10 LCD Default/MM for HC32
    name: Build C2 Default/MM Files HC32
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abl: [MM,Default]
        inshape: [true,false]
        temp: [true,false]
        t5: [true,false]
        t13: [true,false]
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20
    - name: Cache pip
      uses: actions/cache@v4.2.3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4.2.3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Select Python 3.13
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'
    - name: Install PlatformIO
      run: |
        python3 -m pip install --upgrade pip wheel platformio
    - name: Run PlatformIO
      id: build_configs
      run: |
        if ($IS); then ISTMP=-IS; else ISTMP=; fi;
        if ($TP); then TPTMP=-MPC; else TPTMP=; fi;
        if ($T5); then STMP=_SPDY5; else STMP=; fi;
        if ($T13); then TTMP=_SPRT13; else TTMP=; fi;
        > Marlin/Configuration.h
        > Marlin/Configuration_adv.h
        > Marlin/Version.h
        if [ "$ABL" = Default ]; then
        cp configurations/Voxelab\ Aquila\ HC32/C2/Default/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila\ HC32/C2/Default/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila\ HC32/C2/Default/Version.h Marlin/Version.h
        elif [ "$ABL" = MM ]; then
        cp configurations/Voxelab\ Aquila\ HC32/C2/MM/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila\ HC32/C2/MM/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila\ HC32/C2/MM/Version.h Marlin/Version.h
        fi;
        echo "filename=C2_HC32${STMP}${TTMP}_${ABL}${ISTMP}${TPTMP}$(date +"-%m-%d").bin" >> $GITHUB_OUTPUT
        sed -i "s/default_envs =.*/default_envs = HC32F460C_aquila_C2/" platformio.ini
        if ($IS); then STEMP=; else STEMP='\/\/'; fi;
        sed -i "s/.*#define INPUT_SHAPING_X/${STEMP}#define INPUT_SHAPING_X/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Y/${STEMP}#define INPUT_SHAPING_Y/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Z/${STEMP}#define INPUT_SHAPING_Z/" Marlin/Configuration_adv.h
        if ($TP); then PTEMP='\/\/'; MTEMP=; else PTEMP=; MTEMP='\/\/'; fi;
        sed -i "0,/^#define PIDTEMP/ s/.*#define PIDTEMP/${PTEMP}#define PIDTEMP/" Marlin/Configuration.h
        sed -i "s/.*#define MPCTEMP/${MTEMP}#define MPCTEMP/" Marlin/Configuration.h
        if ($T5); then THMP="5"; DSMP="98"; elif ($T13); then THMP="13"; DSMP="424.9"; else THMP="1"; DSMP="98"; fi;
        sed -i "s/^#define TEMP_SENSOR_0.*/#define TEMP_SENSOR_0 ${THMP}/" Marlin/Configuration.h
        sed -i "s/.*#define DEFAULT_AXIS_STEPS_PER_UNIT.*/#define DEFAULT_AXIS_STEPS_PER_UNIT { 80, 80, 400, ${DSMP} }/" Marlin/Configuration.h
        pio run
        mkdir temp
        mv .pio/build/HC32F460C_aquila_C2/*.bin temp/build.bin
      env:
        ABL: ${{ matrix.abl }}
        IS: ${{ matrix.inshape }}
        TP: ${{ matrix.temp }}
        T5: ${{ matrix.t5 }}
        T13: ${{ matrix.t13 }}
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload A Release Asset
      uses: classicrocker883/upload-a-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: temp/build.bin
        asset_name: ${{ steps.build_configs.outputs.filename }}
        asset_content_type: application/x-binary
  Build-C2-Default-MM-A4:            # CR10 LCD Default/MM for Aquila 427
    name: Build C2 Default/MM Files A4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [427,422]
        abl: [MM,Default]
        inshape: [true,false]
        temp: [true,false]
        t5: [true,false]
        t13: [true,false]
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20
    - name: Cache pip
      uses: actions/cache@v4.2.3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4.2.3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Select Python 3.13
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'
    - name: Install PlatformIO
      run: |
        python3 -m pip install --upgrade pip wheel platformio
    - name: Run PlatformIO
      id: build_configs
      run: |
        if [ "$AQUILA_VER" = 427 ]; then AVTMP=_427; DBORD='CREALITY_V427'; else AVTMP=_422; DBORD='CREALITY_V422'; fi;
        if ($IS); then ISTMP=-IS; else ISTMP=; fi;
        if ($TP); then TPTMP=-MPC; else TPTMP=; fi;
        if ($T5); then STMP=_SPDY5; else STMP=; fi;
        if ($T13); then TTMP=_SPRT13; else TTMP=; fi;
        echo "filename=C2${AVTMP}${STMP}${TTMP}_${ABL}${ISTMP}${TPTMP}$(date +"-%m-%d").bin" >> $GITHUB_OUTPUT
        > Marlin/Configuration.h
        > Marlin/Configuration_adv.h
        > Marlin/Version.h
        if [ "$ABL" = Default ]; then
        cp configurations/Voxelab\ Aquila\ 427/Default/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila\ 427/Default/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila\ 427/Default/Version.h Marlin/Version.h
        elif [ "$ABL" = MM ]; then
        cp configurations/Voxelab\ Aquila\ 427/MM/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila\ 427/MM/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila\ 427/MM/Version.h Marlin/Version.h
        fi;
        sed -i "s/default_envs =.*/default_envs = STM32F103RE_creality/" platformio.ini
        sed -i "s/.*#define MOTHERBOARD BOARD_.*/#define MOTHERBOARD BOARD_${DBORD}/" Marlin/Configuration.h
        sed -i "s/.*#define REVERSE_ENCODER_DIRECTION/\/\/#define REVERSE_ENCODER_DIRECTION/" Marlin/Configuration.h
        sed -i "s/.*#define DWIN_LCD_PROUI/\/\/#define DWIN_LCD_PROUI/" Marlin/Configuration.h
        sed -i "s/.*#define CR10_STOCKDISPLAY/#define CR10_STOCKDISPLAY/" Marlin/Configuration.h
        sed -i "s/.*#define LCD_BACKLIGHT_TIMEOUT_MINS.*/\/\/#define LCD_BACKLIGHT_TIMEOUT_MINS/" Marlin/Configuration_adv.h
        if ($IS); then STEMP=; else STEMP='\/\/'; fi;
        sed -i "s/.*#define INPUT_SHAPING_X/${STEMP}#define INPUT_SHAPING_X/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Y/${STEMP}#define INPUT_SHAPING_Y/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Z/${STEMP}#define INPUT_SHAPING_Z/" Marlin/Configuration_adv.h
        if ($TP); then PTEMP='\/\/'; MTEMP=; else PTEMP=; MTEMP='\/\/'; fi;
        sed -i "0,/^#define PIDTEMP/ s/.*#define PIDTEMP/${PTEMP}#define PIDTEMP/" Marlin/Configuration.h
        sed -i "s/.*#define MPCTEMP/${MTEMP}#define MPCTEMP/" Marlin/Configuration.h
        if ($T5); then THMP="5"; DSMP="98"; elif ($T13); then THMP="13"; DSMP="424.9"; else THMP="1"; DSMP="98"; fi;
        sed -i "s/^#define TEMP_SENSOR_0.*/#define TEMP_SENSOR_0 ${THMP}/" Marlin/Configuration.h
        sed -i "s/.*#define DEFAULT_AXIS_STEPS_PER_UNIT.*/#define DEFAULT_AXIS_STEPS_PER_UNIT { 80, 80, 400, ${DSMP} }/" Marlin/Configuration.h
        pio run
        mkdir temp
        mv .pio/build/STM32F103RE_creality/*.bin temp/build.bin
      env:
        AQUILA_VER: ${{ matrix.chip }}
        ABL: ${{ matrix.abl }}
        IS: ${{ matrix.inshape }}
        TP: ${{ matrix.temp }}
        T5: ${{ matrix.t5 }}
        T13: ${{ matrix.t13 }}
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload A Release Asset
      uses: classicrocker883/upload-a-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: temp/build.bin
        asset_name: ${{ steps.build_configs.outputs.filename }}
        asset_content_type: application/x-binary
  Build-C2-Probe-A4:            # CR10 LCD w/Probe for Aquila 427
    name: Build C2 Probe Files A4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [427,422]
        abl: [UBL,BLT]
        inshape: [true,false]
        temp: [true,false]
        t5: [true,false]
        t13: [true,false]
        bmp: [true,false]
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20
    - name: Cache pip
      uses: actions/cache@v4.2.3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4.2.3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Select Python 3.13
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'
    - name: Install PlatformIO
      run: |
        python3 -m pip install --upgrade pip wheel platformio
    - name: Run PlatformIO
      id: build_configs
      run: |
        if [ "$AQUILA_VER" = 427 ]; then AVTMP=_427; DBORD='CREALITY_V427'; else AVTMP=_422; DBORD='CREALITY_V422'; fi;
        if ($IS); then ISTMP=-IS; else ISTMP=; fi;
        if ($TP); then TPTMP=-MPC; else TPTMP=; fi;
        if ($T5); then STMP=_SPDY5; else STMP=; fi;
        if ($T13); then TTMP=_SPRT13; else TTMP=; fi;
        if ($BMP); then MPTMP=_BMP; else MPTMP=; fi;
        echo "filename=C2${AVTMP}${STMP}${TTMP}${MPTMP}_${ABL}${ISTMP}${TPTMP}$(date +"-%m-%d").bin" >> $GITHUB_OUTPUT
        > Marlin/Configuration.h
        > Marlin/Configuration_adv.h
        > Marlin/Version.h
        if [ "$ABL" = BLT ]; then
        cp configurations/Voxelab\ Aquila\ 427/BLT/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila\ 427/BLT/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila\ 427/BLT/Version.h Marlin/Version.h
        elif [ "$ABL" = UBL ]; then
        cp configurations/Voxelab\ Aquila\ 427/UBL/Configuration.h Marlin/Configuration.h
        cp configurations/Voxelab\ Aquila\ 427/UBL/Configuration_adv.h Marlin/Configuration_adv.h
        cp configurations/Voxelab\ Aquila\ 427/UBL/Version.h Marlin/Version.h
        sed -i "s/.*#define MESH_EDIT_GFX_OVERLAY/#define MESH_EDIT_GFX_OVERLAY/" Marlin/Configuration.h
        sed -i "s/.*#define UBL_MESH_WIZARD/#define UBL_MESH_WIZARD/" Marlin/Configuration.h
        fi;
        sed -i "s/default_envs =.*/default_envs = STM32F103RE_creality/" platformio.ini
        sed -i "s/.*#define MOTHERBOARD BOARD_.*/#define MOTHERBOARD BOARD_${DBORD}/" Marlin/Configuration.h
        sed -i "s/.*#define REVERSE_ENCODER_DIRECTION/\/\/#define REVERSE_ENCODER_DIRECTION/" Marlin/Configuration.h
        sed -i "s/.*#define DWIN_LCD_PROUI/\/\/#define DWIN_LCD_PROUI/" Marlin/Configuration.h
        sed -i "s/.*#define CR10_STOCKDISPLAY/#define CR10_STOCKDISPLAY/" Marlin/Configuration.h
        sed -i "s/.*#define LCD_BACKLIGHT_TIMEOUT_MINS.*/\/\/#define LCD_BACKLIGHT_TIMEOUT_MINS/" Marlin/Configuration_adv.h
        if ($IS); then STEMP=; else STEMP='\/\/'; fi;
        sed -i "s/.*#define INPUT_SHAPING_X/${STEMP}#define INPUT_SHAPING_X/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Y/${STEMP}#define INPUT_SHAPING_Y/" Marlin/Configuration_adv.h
        sed -i "s/.*#define INPUT_SHAPING_Z/${STEMP}#define INPUT_SHAPING_Z/" Marlin/Configuration_adv.h
        if ($TP); then PTEMP='\/\/'; MTEMP=; else PTEMP=; MTEMP='\/\/'; fi;
        sed -i "0,/^#define PIDTEMP/ s/.*#define PIDTEMP/${PTEMP}#define PIDTEMP/" Marlin/Configuration.h
        sed -i "s/.*#define MPCTEMP/${MTEMP}#define MPCTEMP/" Marlin/Configuration.h
        if ($T5); then THMP="5"; DSMP="98"; elif ($T13); then THMP="13"; DSMP="424.9"; else THMP="1"; DSMP="98"; fi;
        sed -i "s/^#define TEMP_SENSOR_0.*/#define TEMP_SENSOR_0 ${THMP}/" Marlin/Configuration.h
        sed -i "s/.*#define DEFAULT_AXIS_STEPS_PER_UNIT.*/#define DEFAULT_AXIS_STEPS_PER_UNIT { 80, 80, 400, ${DSMP} }/" Marlin/Configuration.h
        if ($BMP); then MPDEMP=; MPEMP='\/\/'; MPHS="LOW"; else MPDEMP='\/\/'; MPEMP=; MPHS="HIGH"; fi;
        sed -i "s/.*#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN/${MPDEMP}#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN/" Marlin/Configuration.h
        sed -i "s/.*#define Z_MIN_ENDSTOP_HIT_STATE.*/#define Z_MIN_ENDSTOP_HIT_STATE ${MPHS}/" Marlin/Configuration.h
        sed -i "s/.*#define Z_MIN_PROBE_ENDSTOP_HIT_STATE.*/#define Z_MIN_PROBE_ENDSTOP_HIT_STATE ${MPHS}/" Marlin/Configuration.h
        sed -i "s/.*#define BLTOUCH/${MPEMP}#define BLTOUCH/" Marlin/Configuration.h
        sed -i "s/.*#define BIQU_MICROPROBE_V2/${MPDEMP}#define BIQU_MICROPROBE_V2/" Marlin/Configuration.h
        sed -i "s/.*#define PROBE_ENABLE_DISABLE/${MPDEMP}#define PROBE_ENABLE_DISABLE/" Marlin/Configuration.h
        pio run
        mkdir temp
        mv .pio/build/STM32F103RE_creality/*.bin temp/build.bin
      env:
        AQUILA_VER: ${{ matrix.chip }}
        ABL: ${{ matrix.abl }}
        IS: ${{ matrix.inshape }}
        TP: ${{ matrix.temp }}
        T5: ${{ matrix.t5 }}
        T13: ${{ matrix.t13 }}
        BMP: ${{ matrix.bmp }}
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload A Release Asset
      uses: classicrocker883/upload-a-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: temp/build.bin
        asset_name: ${{ steps.build_configs.outputs.filename }}
        asset_content_type: application/x-binary
