#
# lock-closed.yml
# Lock closed issues after a period of inactivity
#

name: Lock Closed Issues

on:
  schedule:
    - cron: '0 1 1 */2 *'

jobs:
  lock:
    name: Lock Closed Issues
    if: github.repository == 'classicrocker883/MRiscoCProUI'

    runs-on: ubuntu-latest

    steps:
    - uses: dessant/lock-threads@v5.0.1
      with:
        github-token: ${{ github.token }}
        process-only: 'issues'
        issue-inactive-days: '60'
        exclude-issue-created-before: ''
        exclude-any-issue-labels: 'no-locking'
        add-issue-labels: ''
        issue-comment: >
          This issue has been automatically locked since there
          has not been any recent activity after it was closed.
          Please open a new issue for related bugs.
        issue-lock-reason: ''
